In [1]:
import numpy as np

In [6]:
a = np.arange(12).reshape(3,4)


In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
#no of ways to iterate
for rows in a:
    print(rows)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [11]:
#if you want to iterate rows
for rows in a:
    for cell in rows:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
#we can do above as
b = a.flatten()

In [14]:
for cell in b:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# nditer

In [15]:
                        #will go row by row
for x in np.nditer(a,order = 'C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
#to go column by columns
for c in np.nditer(a,order = 'F'):
    print(c)

0
4
8
1
5
9
2
6
10
3
7
11


# Flags of nditer

In [19]:
#printing columns instead of the cells
for x in np.nditer(a, order = 'F', flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
